import { Router } from "express";
import { SaveLinks, EditLinkdata, EditCustomTag, DeleteTags, DeleteLinks } from "../Controllers/Linkdata.controller.js";
import { VerifyJWT } from "../Middleware/Auth.middleware.js";
const Routers = Router();
Routers.route("/Mainpage").post(VerifyJWT, SaveLinks);
Routers.route("/Editpage/:id").patch(VerifyJWT, EditLinkdata);
Routers.route("/Edittags/:id").patch(VerifyJWT, EditCustomTag);
Routers.route("/Deletelinks/:id").delete(VerifyJWT, DeleteLinks);
Routers.route("/Deletetags/:id").delete(VerifyJWT, DeleteTags);
export default Routers;
